#!/usr/bin/env bash

# Based on https://github.com/TheLocehiliosan/yadm/blob/master/contrib/bootstrap/bootstrap-in-dir

set -euo pipefail

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

if [[ ! -d "$BOOTSTRAP_D" ]]; then
	echo "Error: bootstrap directory '${BOOTSTRAP_D}' not found" >&2
	exit 1
fi

while IFS= read -r -d '' BOOTSTRAP; do
	if [[ ! -x "$BOOTSTRAP" || "$BOOTSTRAP" =~ "##" || "$BOOTSTRAP" =~ "~$" ]]; then
		continue
	fi

	if ! "$BOOTSTRAP"; then
		echo "Error: bootstrap '$BOOTSTRAP' failed" >&2
		exit 1
	fi
done < <(find -L "$BOOTSTRAP_D" -type f -print0 | sort -z)
